# Generated by Django 2.2.12 on 2021-05-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=0, verbose_name='Номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('av_grade', models.IntegerField(default=0, verbose_name='Средняя оценка')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_fio', models.TextField(verbose_name='ФИО родителей')),
                ('parents_contacts', models.TextField(verbose_name='Контакты родителей')),
                ('st_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme', models.CharField(max_length=200, verbose_name='Тема урока')),
                ('presence', models.BooleanField(default=False, verbose_name='Присутствие')),
                ('grade', models.IntegerField(default=0, verbose_name='Оценка')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_theme', models.CharField(max_length=200, verbose_name='Тема домашнего задания')),
                ('homework', models.TextField(verbose_name='Текст домашнего задания')),
                ('hw_date', models.DateField()),
                ('hw_grade', models.IntegerField(default=0, verbose_name='Оценка за домашнее задание')),
                ('hw_done', models.BooleanField(default=False, verbose_name='Выполнено ли ДЗ')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_work_title', models.CharField(max_length=200, verbose_name='Тема контрольно работы')),
                ('exam_work_text', models.TextField(verbose_name='Текст контрольной работы')),
                ('exam_work_grade', models.IntegerField(default=0, verbose_name='Оценка за контрольную работу')),
                ('exam_work_done', models.BooleanField(default=False, verbose_name='Сдано')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Group')),
            ],
        ),
    ]
